disabled_rules: # rule identifiers to exclude from running
  #- colon
  #- comma
  #- control_statement
  - trailing_whitespace
  - large_tuple
  - nesting
  - block_based_kvo
  - function_parameter_count
  - unused_optional_binding
  - valid_ibinspectable
  - implicit_getter

opt_in_rules: # some rules are only opt-in
  - empty_count

excluded:
- Carthage
- Pods

  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - PixiView

# configurable rules can be customized from this configuration file
line_length:
    warning: 700
    error: 800
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

# they can set both implicitly with an array
type_body_length:
  - 1000 # warning
  - 1100 # error

# or they can set both explicitly
file_length:
  warning: 1100
  error: 1500

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 60
    error: 70
  excluded: iPhone # excluded via string

cyclomatic_complexity:
  warning: 90
  error: 100

identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 60
    error: 70
  validates_start_with_lowercase: false
  min_length: # only min_length
    warning: 0
    error: 0 # only error
  excluded: # excluded via string array
    - i
    - j
    - id
    - URL
    - url
    - GlobalAPIKey
    - open
    - app
    - hex
    - POST
    - GET
    - PUT
    - sms
    - lhs
    - rhs
    - row
    - use

    - !str yes
    - !str no
    - ok
    - key
    - hex
    - int
    - top
    - nt
    - web
    - add
    - !str on
    - !str off

function_body_length:
    - 175
    - 200

function_parameter_count:
    - 8
    - 10
    
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

